// Generate experiments/browser-qa/INDEX.md from the runs' meta.json files —
// one line per run (TEST_HYGIENE R3): date · suite · label · host · sha ·
// headline · verdict. Never maintained by hand.
import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const runsDir = join(dirname(fileURLToPath(import.meta.url)), '..', 'experiments', 'browser-qa', 'runs')
if (!existsSync(runsDir)) { console.error('no runs/'); process.exit(1) }
const rows = []
for (const label of readdirSync(runsDir).sort()) {
  const metaPath = join(runsDir, label, 'meta.json')
  if (!existsSync(metaPath)) continue
  const m = JSON.parse(readFileSync(metaPath, 'utf8'))
  rows.push(`| ${m.started.slice(0, 10)} | ${m.suite} | ${m.label} | ${m.host} | \`${m.sha}\`${m.dirty ? '-dirty' : ''} | ${m.headline} | ${m.verdict === 'pass' ? 'pass' : '**FAIL**'} |`)
}
const out = join(dirname(fileURLToPath(import.meta.url)), '..', 'experiments', 'browser-qa', 'INDEX.md')
writeFileSync(out, [
  '# Browser QA runs',
  '',
  'Generated by `node scripts/gen-index.mjs` — do not edit by hand.',
  '',
  'date · suite · label · host · sha · headline · verdict',
  '',
  '| date | suite | label | host | sha | headline | verdict |',
  '|---|---|---|---|---|---|---|',
  ...rows,
  '',
].join('\n'))
console.log(`INDEX.md: ${rows.length} run(s)`)
