// One-off migration: slice the seven monolithic theme strings into
// tokens (the :root block, vision themes' @font-face included) plus named
// component fragments, preserving exact bytes and original rule order.
//
// Safety model: the script refuses to write anything unless every theme
// reconstructs byte-for-byte from its slices (assertReconstruction), and
// every top-level rule classifies into a known family (the classifier
// throws on unmatched selectors). Run: node scripts/split-themes.mjs
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const here = dirname(fileURLToPath(import.meta.url))
const { themes, mobileLayer } = await import(join(here, '../dist/index.js'))

// selector -> component family; first match wins, order matters
const FAMILY = [
  [/^html$|^body$|^code, pre$|^\*/, 'base'],
  [/^\.pp-|^a$|^a:hover$|^pre$/, 'page'],
  [/^\.sure-form/, 'form'],
  [/^\.sure-modal/, 'modal'],
  [/^\.sure-dialog/, 'dialog'],
  [/^\.sure-table/, 'table'],
  [/^\.sure-crud/, 'crud'],
  [/^\.sure-search/, 'search'],
  [/^\.btn-/, 'buttons'],
  [/^\.toast|^@keyframes slideIn/, 'toast'],
  [/^\.status-bar/, 'status'],
  [/^\.side-panel/, 'sidepanel'],
  [/^\.sure-auth/, 'auth'],
  [/^\.sure-markdown/, 'markdown'],
  [/^\.sure-session|^\.msg-|^\.message/, 'sessions'],
  [/^\.sure-menu/, 'menu'],
  [/^\.sure-toolbar|^\.sure-filters|^\.sure-note|^\.sure-panel|^\.sure-help/, 'regions'],
  [/^\.sure-toggle|^\.sure-row-actions|^\.sure-nav__|^\.visually-hidden/, 'composites'],
]

function classify(sel) {
  const s = sel.replace(/\s+/g, ' ').trim()
  for (const [re, fam] of FAMILY) if (re.test(s)) return fam
  throw new Error(`unclassified selector: ${JSON.stringify(s.slice(0, 90))}`)
}

// Split into top-level rules with byte spans; leading comments/whitespace
// before each selector stay attached to that rule.
function rulesWithSpans(css) {
  const out = []
  let i = 0
  while (i < css.length) {
    const start = i
    const open = css.indexOf('{', i)
    if (open < 0) break
    const selRaw = css.slice(i, open)
    let depth = 0, k = open
    for (; k < css.length; k++) {
      if (css[k] === '{') depth++
      else if (css[k] === '}') { depth--; if (depth === 0) break }
    }
    const end = k + 1
    const sel = selRaw.replace(/\/\*[\s\S]*?\*\//g, '').trim()
    out.push({ sel, start, end, fam: sel.startsWith(':root') || sel.startsWith('@font-face') ? 'tokens' : classify(sel) })
    i = end
  }
  return out
}

function sliceTheme(name, full) {
  if (!full.endsWith(mobileLayer)) throw new Error(`${name}: missing mobile layer suffix`)
  const css = full.slice(0, -mobileLayer.length)

  const rules = rulesWithSpans(css)
  if (!rules.length || rules[0].fam !== 'tokens') throw new Error(`${name}: does not start with tokens`)

  // tokens = everything through the end of the :root block (@font-face rides along)
  const rootEnd = rules.filter(r => r.fam === 'tokens').at(-1).end
  const tokens = css.slice(0, rootEnd)

  // runs: contiguous slices of one family, in original order. A family can
  // appear in several runs (e.g. `.sure-table tr.is-selected` lives in the
  // state-hooks section, far from the table block), so runs — not a
  // family-keyed map — are what preserves bytes exactly.
  const runs = []
  let pendingStart = rootEnd
  let runFam = null, runEnd = null
  const flush = () => {
    if (!runFam) return
    if (runFam === 'tokens') { pendingStart = runEnd; runFam = null; return }
    runs.push([runFam, css.slice(pendingStart, runEnd)])
    pendingStart = runEnd
    runFam = null
  }
  for (const r of rules.slice(1)) {
    if (r.fam !== runFam) { flush(); runFam = r.fam }
    runEnd = r.end
  }
  flush()
  // trailing bytes after the last rule (whitespace) join the last run
  if (pendingStart < css.length && runs.length) {
    runs[runs.length - 1][1] += css.slice(pendingStart)
  }

  const rebuilt = tokens + runs.map(([, s]) => s).join('')
  if (rebuilt !== css) throw new Error(`${name}: reconstruction mismatch (${rebuilt.length} vs ${css.length})`)
  return { tokens, runs }
}

const out = {}
for (const [name, full] of Object.entries(themes)) out[name] = sliceTheme(name, full)

const esc = (s) => s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${')

let ts = `// GENERATED by scripts/split-themes.mjs from the 0.1.9 theme strings.
// Do not edit by hand: edit the shared component blocks (0.2.0b) instead.
// Reconstruction is proven byte-for-byte by tests (fixtures/themes-0.1.9.json).
export const tokens: Record<string, string> = {\n`
for (const [name, t] of Object.entries(out)) ts += `  '${name}': \`${esc(t.tokens)}\`,\n`
ts += `}\n\nexport const runs: Record<string, Array<[string, string]>> = {\n`
for (const [name, t] of Object.entries(out)) {
  ts += `  '${name}': [\n`
  for (const [fam, s] of t.runs) ts += `    ['${fam}', \`${esc(s)}\`],\n`
  ts += `  ],\n`
}
ts += `}\n`

writeFileSync(join(here, '../src/generated/themes.ts'), ts)

// frozen consumer-visible bytes of 0.1.9 (mobile layer included) for the
// equivalence test
writeFileSync(join(here, '../src/__fixtures__/themes-0.1.9.json'), JSON.stringify(themes, null, 0) + '\n')

const fams = [...new Set(Object.values(out).flatMap(t => t.runs.map(([f]) => f)))].sort()
console.log('families:', fams.join(', '))
for (const [name, t] of Object.entries(out)) {
  const sizes = Object.entries(t.runs.reduce((a, [f, s]) => ((a[f] = (a[f] ?? 0) + s.length), a), {})).map(([f, n]) => `${f}:${n}`).join(' ')
  console.log(`${name.padEnd(16)} tokens:${t.tokens.length} ${sizes}`)
}
console.log('reconstruction: byte-identical for all', Object.keys(out).length, 'themes')
